### ISSUE TITLE
Distillied Model -  Sequence To Sequence Encoder 

### ISSUE THREAD

**Issue by felipesantosk** [felipesantosk/bergamot-translator#2]
On the deepQuest, it is using a [`seq2seq_encoder` from allennlp](http://docs.allennlp.org/v0.9.0/api/allennlp.modules.seq2seq_encoders.html) with a torch gru-cell, where the bias and bidirectional are enable. The operation GRU is calculated on this code in the end.

![calculation](https://user-images.githubusercontent.com/42920697/155991027-5063177d-6d22-4371-881b-66e2e7ecfd7f.png)

So, on the python side there are these weights:

```
weight_ih (torch.Tensor) – the learnable input-hidden weights, of shape (3*hidden_size, input_size)
weight_hh (torch.Tensor) – the learnable hidden-hidden weights, of shape (3*hidden_size, hidden_size)
bias_ih – the learnable input-hidden bias, of shape (3*hidden_size)
bias_hh – the learnable hidden-hidden bias, of shape (3*hidden_size)
```

On the marian side, There is a [S2SEnconder](https://github.com/browsermt/marian-dev/blob/master/src/models/s2s.h) where I can enable the bidirectional and gru cell.
The first problem that I faced was the Marian GRU parameters, each weight type is split into two parameters and [after read they are concatenated](https://github.com/browsermt/marian-dev/blob/master/src/rnn/cells.h#L227-L243).

```
_W  – {dimState, 2 * dimState} 
_Wx – {dimState, dimState} 
_U  – {dimState, 2 * dimState} 
_Ux – {dimState, dimState} 
_b  – {2 * dimState} 
_bx – {dimState} 
```

To ignore this problem for now, I just read the expected parameter after the concat, following a [pre-existed commented code](https://github.com/browsermt/marian-dev/blob/master/src/rnn/cells.h#L245-L251).

Read parameters changes: https://github.com/felipesantosk/marian-dev/blob/seq2seq_change_parameters/src/rnn/cells.h#L246-L248

The second problem was the hidden bias, on the Marian, it not exists on the [tensor operation](https://github.com/browsermt/marian-dev/blob/master/src/tensors/cpu/tensor_operators.cpp#L801). So I changed to [load hidden bias](https://github.com/felipesantosk/marian-dev/blob/seq2seq_change_parameters/src/rnn/cells.h#L249) and apply the [sum after the hidden dot operation](https://github.com/felipesantosk/marian-dev/blob/seq2seq_change_parameters/src/rnn/cells.h#L305).
But in the end only the first values are the same as expected.

```
Marian - Distilled Model Results 
[-0.00367 -0.0299   0.08585 -0.09392 -0.00356 -0.05758  0.00477  0.0038
  0.0315   0.03067  0.09183 -0.0082   0.05453  0.00718  0.08878  0.03864
  0.04614  0.07656  0.02339  0.04052 -0.06039 -0.02121  0.04143  0.04657
 -0.07244 -0.01103 -0.01347  0.01201 -0.05846 -0.03344 -0.00448  0.01495
 -0.07299  0.01476 -0.01538  0.10016 -0.02006 -0.01338 -0.05996  0.00847
 -0.03463  0.09196 -0.04631 -0.00992 -0.02088  0.00752 -0.00685 -0.0093
 -0.05815  0.04854  0.05376  0.02058  0.01224  0.01795 -0.02055  0.04209
 -0.03216 -0.03655 -0.01628 -0.03209  0.07463 -0.00181  0.03953  0.02514
  0.08512  0.04648 -0.01957 -0.08162 -0.10521 -0.00123  0.0063  -0.09443
 -0.04427  0.07849 -0.02365 -0.05162  0.06276 -0.06375 -0.05258  0.01513
  0.049    0.04584  0.06971 -0.07391  0.00475 -0.01307  0.0009   0.06742
  0.02021  0.05309 -0.08115  0.11572 -0.00379 -0.08908 -0.00208  0.07497
 -0.00895 -0.03122 -0.04389  0.06144]
...
DEEPQUEST - Expected Values
[-0.00367 -0.0299   0.08585 -0.09392 -0.00356 -0.05758  0.00477  0.0038
  0.0315   0.03067  0.09183 -0.0082   0.05453  0.00718  0.08878  0.03864
  0.04614  0.07656  0.02339  0.04052 -0.06039 -0.02121  0.04143  0.04657
 -0.07244 -0.01103 -0.01347  0.01201 -0.05846 -0.03344 -0.00448  0.01495
 -0.07299  0.01476 -0.01538  0.10016 -0.02006 -0.01338 -0.05996  0.00847
 -0.03463  0.09196 -0.04631 -0.00992 -0.02088  0.00752 -0.00685 -0.0093
 -0.05815  0.04854  0.1004   0.23042  0.06153  0.0981   0.06815  0.10054
  0.1085  -0.10147 -0.10121 -0.08835  0.28434  0.08787  0.14117  0.1264
  0.24925  0.12489 -0.1345  -0.23427 -0.28259 -0.06598  0.04986 -0.18211
  0.00975  0.21946  0.15744 -0.16252  0.10696 -0.22769 -0.05516  0.12679
  0.18564  0.18043  0.20503 -0.2099   0.15294 -0.15871 -0.03643  0.24563
  0.02949  0.08492 -0.19227  0.32272 -0.00134 -0.23051 -0.01733  0.17576
  0.02849 -0.05159 -0.09878  0.19715]
...
```

The files with the marian (marian_results.npz) and deepquest results (distillied_py_results.npz) are on the compressed file [distillied_results.zip](https://github.com/felipesantosk/bergamot-translator/files/8153798/distillied_results.zip) and I changed the compare script to print the beginning of the tensor.

Changed Marian: https://github.com/felipesantosk/marian-dev/blob/seq2seq_change_parameters/src/rnn/cells.h#L227-L326
Distilled : https://github.com/felipesantosk/bergamot-translator/blob/distilled-model_src_seq2seq/distilled/main.cpp
Compare script: https://github.com/felipesantosk/bergamot-translator/blob/distilled-model_src_seq2seq/distilled/compare_marian_with_deepquest.py

**Comment by jerinphilip** [comment]
@felipesantosk Appreciate the depths you're pursuing this in this repository for a solution. With the limited capabilities here to assess, we suspect there might be some mismatch in the matrix parameters load happening which is leading to differing outputs. There should be a C++ equivalent (expressed in Marian's graph) of the PyTorch code, which should give you the correct results.

I'd prefer to convey early on that it is very hard to be pointed at lines sitting in a branch and then leave comments. If this were a pull request (which supports review comments) it would make things simpler - with a UI where we can directly comment on code and can view the bigger context of edits. I request you to do the following as soon as possible to help ease communication.

1. Open a deepQuest integration PR against [browsermt/bergamot-translator@main](https://github.com/browsermt/bergamot-translator).
2. Open a corresponding deepQuest integration PR against [browsermt/marian-dev@main](https://github.com/browsermt/bergamot-translator). (1) will use the branch corresponding to this PR as submodule.

Both (1), (2) could be WIP draft PRs. Expect (1), (2) to get merged eventually if deepQuest at the end is feasible. In the PR descriptions, I expect checkboxes (print the model in Python torch representation and how many layers have been ported) to track progress.

Additionally, what you've mentioned here in writing, try to leave in comments (descriptive) near the code that pertains to the same.  As of now, we are having to click links and do back and forth to figure out what's going on. 

cc @graemenail

**Comment by graemenail** [comment]
Hi @felipesantosk - I may have missed it, but is `distilled.npz` available somewhere? Would be useful if we can reproduce your output.

I had a look through the code and it does seem the PyTorch GRU implementation has an additional bias term. Looking at your output, the first 50 entries match, but the second 50 do not, which I believe would correspond to the context from the backward RNN.

**Comment by felipesantosk** [comment]
@jerinphilip  

I created the PRs:
- bergamot-translator : https://github.com/browsermt/bergamot-translator/pull/364
- marian-dev - https://github.com/browsermt/marian-dev/pull/76
- felipesantosk/bergamot-translator : https://github.com/felipesantosk/bergamot-translator/pull/3

These PRs still not ready for production, the last one has the sequence to sequence enconder implementaion with the problem that I'm facing. 

@graemenail 

Here are the files. 
[distilled.zip](https://github.com/felipesantosk/bergamot-translator/files/8164177/distilled.zip)

The `distilled.npz` has the weights read by marian and the `weights.th` is the original weights from deepQuest.
